# Generated by Django 5.2.6 on 2025-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuracoes', '0003_alter_procuracao_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procuracao',
            name='status',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Expirada', 'Expirada'), ('Renovada', 'Renovada')], default='Ativa', max_length=10, verbose_name='Status'),
        ),
    ]
