# Generated by Django 5.2.6 on 2025-09-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuracoes', '0004_alter_procuracao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procuracao',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], max_length=10, verbose_name='Prioridade'),
        ),
    ]
