# Generated by Django 5.2.6 on 2025-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuracoes', '0005_alter_procuracao_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procuracao',
            name='prioridade',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='procuracao',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('expired', 'Expirada'), ('renewed', 'Renovada')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='procuracao',
            name='tipo',
            field=models.CharField(choices=[('AD_JUDICIA', 'Ad Judicia'), ('FINANCEIRA', 'Financeira'), ('GERAL', 'Geral')], default='AD_JUDICIA', max_length=50, verbose_name='Tipo de Procuração'),
        ),
    ]
